language: objective-c
script: 
  - xctool -project {{Demo/Demo.xcodeproj}} -scheme {{DemTestso.xcodeproj}} build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
